#pragma once

// defines event: an object which holds what changed
// events are generated by physics && are passed to graphincs && are applied

#include <memory>
#include <vector>

#include "objects/AnimateObject.h"
#include "objects/MapConstants.h"
#include "objects/Block.h"
#include "control/MoveDirection.h"

using ObjectPtr = std::shared_ptr<AnimateObject>;

class Event
{
public:
	enum struct Type
	{
		Move,
		Kill,
		Promote,
		Demote,
		EatPoint,
		DestroyWall,
		AddWall,
		Nothing
	};
	// creators of specific events
	friend Event event_move(MoveDirection, ObjectPtr);
	friend Event event_kill(ObjectPtr);
	friend Event event_promote(ObjectPtr);
	friend Event event_demote(ObjectPtr);
	friend Event event_eat_point(Coordinate, Coordinate);
	friend Event event_destroy_wall(Coordinate, Coordinate);
	friend Event event_add_wall(Coordinate, Coordinate, Block);
	friend Event event_nothing();

	Event(const Type&, const ObjectPtr&, const Coordinate&,
	      const Coordinate&, const MoveDirection&, const Block&);

	Type          get_type() const;
	ObjectPtr     get_object_argument() const;
	Coordinate    get_coordinate_argument_x() const;
	Coordinate    get_coordinate_argument_y() const;
	MoveDirection get_direction_argument() const;
	Block         get_block_argument() const;

private:
	Type          m_type;
	ObjectPtr     m_object_argument;
	Coordinate    m_coordinate_argument_x;
	Coordinate    m_coordinate_argument_y;
	MoveDirection m_direction_argument;
	Block         m_block_argument;
};


// vim: tw=78
